project/births/forms.py
# project/recipes/forms.py
 
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import StringField, DateField, IntegerField, validators, ValidationError, SelectField
from wtforms.validators import DataRequired, Length, EqualTo, Email


def RepresentsInt(s):
    try: 
        int(s)
        return True
    except ValueError:
        return False

def check_int(form, field):
    if RepresentsInt(field.data) == True:
        raise ValidationError('No numeric values are allowed')


 
 
class AddBirthForm(Form):
    child_name = StringField('Name of Child', [DataRequired(), check_int])
    father_name = StringField('Name of Father', validators=[DataRequired(), check_int])
    mother_name = StringField('Name of Mother', validators=[DataRequired(), check_int])
    gender = SelectField('Gender', choices=[('Male', 'Male'),('Female', 'Female')])
    birth_year = SelectField('Year of Birth', choices=[('1971', '1971'),('1972', '1972'),('1973', '1973'),('1974', '1974'),('1975', '1975'),('1976', '1976'),('1977', '1977'),('1978', '1978'),('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018') ], validators=[DataRequired()])
    birth_county = SelectField('County', choices=[('Mombasa', 'Mombasa'),('Kwale', 'Kwale'),('Kilifi', 'Kilifi'),('Tana River', 'Tana River'),('Lamu', 'Lamu'),('Taita Taveta', 'Taita Taveta'),('Garissa', 'Garissa'),('Wajir', 'Wajir'),('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Muranga', 'Muranga'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], validators=[DataRequired()])
    


class UpdateBirthForm(Form):
    child_name = StringField('Name of Child', [DataRequired(), check_int])    
    birth_year = SelectField('Year of Birth', choices=[('1971', '1971'),('1972', '1972'),('1973', '1973'),('1974', '1974'),('1975', '1975'),('1976', '1976'),('1977', '1977'),('1978', '1978'),('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018') ], validators=[DataRequired()])
    birth_county = SelectField('County', choices=[('Mombasa', 'Mombasa'),('Kwale', 'Kwale'),('Kilifi', 'Kilifi'),('Tana River', 'Tana River'),('Lamu', 'Lamu'),('Taita–Taveta', 'Taita–Taveta'),('Garissa', 'Garissa'),('Wajir', 'Wajir'),('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Muranga', 'Muranga'), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi') ], validators=[DataRequired()])

project/id/forms.py
from flask_wtf import Form
from wtforms import IntegerField
from wtforms.validators import DataRequired, Length, NumberRange
from flask_wtf.file import FileField, FileAllowed, FileRequired
from project import images
 
 
class AddIDForm(Form):
    id_number = IntegerField('ID Number', validators=[DataRequired(), NumberRange(min=30000000, max=40000000)])
    birth_id = IntegerField('Birth ID', validators=[DataRequired(), NumberRange(min=1, max=9)])
    profile_image = FileField('Profile Photo', validators=[FileRequired(), FileAllowed(images, 'Images only!')])

project/births/views.py
# project/recipes/views.py
 
#################
#### imports ####
#################
 
from flask import render_template, Blueprint, request, redirect, url_for, flash
from project import db
from project.models import Birth, ID, IEBC
from project.births.forms import AddBirthForm
from flask_login import login_user, current_user, login_required, logout_user

 
def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')
 
################
#### config ####
################
 
births_blueprint = Blueprint('births', __name__)
 
 
################
#### routes ####
################
 

def method_is_delete(request):
    '''Workaround for a lack of delete method is the HTML spec for forms.'''
    return request.form.get('_method') == 'DELETE'


        # delete somehing




@births_blueprint.route('/births_list')
@login_required
def index():
    all_births = Birth.query.all()
    if current_user.username == 'Registrar':
        return render_template('births.html', births=all_births)
    else:
        return render_template('403.html')


@births_blueprint.route('/list_of_persons')
@login_required
def list_of_persons():
    all_ids = db.session.query(Birth,ID).filter(Birth.id == ID.birth_id).all()
    if current_user.username == 'Registrar':
        return render_template('list_of_persons.html', ids=all_ids)
    else:
        flash('Error! Incorrect permissions to access this record.', 'error')
        return render_template('403.html')


@births_blueprint.route('/mark_as_deceased/<birth_id>')
@login_required
def mark_as_deceased(birth_id):
    birth = Birth.query.get_or_404(birth_id)
        #a = Birth.query.filter(Birth.deceased == False).all()
    birth.deceased = True
    db.session.commit()
    return redirect(url_for('iebc.index'))


@births_blueprint.route('/person_detail/<id_card_id>')
@login_required
def person_details(id_card_id):
    all_voters = db.session.query(Birth, ID).join(ID).filter(ID.id == id_card_id).first()
    print (all_voters)
    if all_voters is not None:        
        if current_user.is_authenticated and current_user.username == 'Registrar':
            return render_template('person_details.html', voters=all_voters)
        else:
            flash('Error! Incorrect permissions to access this record.', 'error')
    else:
        flash('Error! Record does not exist.', 'error')


@births_blueprint.route('/add', methods=['GET', 'POST'])    # Use of @roles_required decorator
@login_required
def add_birth():
    form = AddBirthForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_birth = Birth(form.child_name.data, form.father_name.data, form.mother_name.data, form.gender.data, form.birth_year.data, form.birth_county.data, False, False, False)
            db.session.add(new_birth)
            db.session.commit()
            flash('New Birth Record, {}, added!'.format(new_birth.child_name), 'success')
            if current_user.username == 'Registrar':
                return redirect(url_for('births.index'))
        else:
        	flash_errors(form)
        	flash('ERROR! Record was not added.', 'error')
 
    return render_template('add_birth.html',
                           form=form)


@births_blueprint.route('/birth/<birth_id>')
@login_required
def birth_details(birth_id):
    birth = db.session.query(Birth).filter(Birth.id == birth_id).first()
    if birth is not None:        
        if current_user.username == 'Registrar':
            return render_template('birth_details.html', birth=birth)
        else:
            flash('Error! Incorrect permissions to access this record.', 'error')
    else:
        flash('Error! Record does not exist.', 'error')
    return redirect(url_for('births.index'))


@births_blueprint.route('/birth_with_ID/<birth_id>')
def birth_with_ID_details(birth_id):
    birth = db.session.query(Birth).filter(Birth.id == birth_id).first()
    if birth is not None:        
        if current_user.is_authenticated:
            return render_template('add_id_number.html', birth=birth)
        else:
            flash('Error! Incorrect permissions to access this record.', 'error')
    else:
        flash('Error! Record does not exist.', 'error')
    return redirect(url_for('births.index'))

project/id/views.py
import string
import random
import datetime
import dateutil
from flask import render_template, Blueprint, request, redirect, url_for, flash, abort
from flask_login import login_user, current_user, login_required, logout_user
from project.id.forms import AddIDForm
from project.models import ID, Birth
from project import db, images

id_blueprint = Blueprint('id', __name__)

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')

def birthday(date):
    # Get the current date
    now = 2018
    age = now - date

    return age

def id_generator(size=8, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))




@id_blueprint.route('/id_list')
@login_required
def index():
    all_ids = db.session.query(Birth,ID).join(ID).filter(Birth.id == ID.birth_id, Birth.has_id == True).all()
    if current_user.username == 'IDAdmin':
        return render_template('ids.html', ids=all_ids)
    else:
        flash('Error! Incorrect permissions to access this record.', 'error')
        return render_template('403.html')


@id_blueprint.route('/qualified_id_list')
@login_required
def qualified_id_list():
    all_ids = db.session.query(Birth).filter(birthday(Birth.birth_year) >= 18, Birth.has_id == False).all()
    if current_user.username == 'IDAdmin':
        return render_template('qualified_id_list.html', ids=all_ids)
    else:
        flash('Error! Incorrect permissions to access this record.', 'error')
        return render_template('403.html')



@id_blueprint.route('/unregistered_id_list')
@login_required
def unregistered_id_list():
    all_births = db.session.query(Birth).filter(birthday(Birth.birth_year) >= 18, Birth.has_id == False).all()
    if current_user.username == 'IDAdmin':
        return render_template('unregistered_ids.html', births=all_births)
    else:
        flash('Error! Incorrect permissions to access this record.', 'error')
        return render_template('403.html')



@id_blueprint.route('/add_id_number/<birth_id>')
@login_required
def add_id_number(birth_id):
    all_births = Birth.query.get_or_404(birth_id)
    if current_user.username == 'IDAdmin':
        return render_template('add_id_number.html', births=all_births)
    else:
        flash('Error! Incorrect permissions to access this record.', 'error')
        return render_template('403.html')

@id_blueprint.route('/mark_as_allocated/<birth_id>')
@login_required
def mark_as_allocated(birth_id):
    birth = Birth.query.get_or_404(birth_id)
        #a = Birth.query.filter(Birth.deceased == False).all()
    birth.has_id = True
    db.session.commit()
    return redirect(url_for('id.index'))


@id_blueprint.route('/id_allocation_detail/<id_card_id>')
@login_required
def id_allocation_details(id_card_id):
    all_voters = db.session.query(Birth, ID).join(ID).filter(ID.id == id_card_id).first()
    if all_voters is not None:        
        if current_user.is_authenticated and current_user.username == 'IDAdmin':
            return render_template('id_allocation_details.html', voters=all_voters)
        else:
            flash('Error! Incorrect permissions to access this record.', 'error')
    else:
        flash('Error! Record does not exist.', 'error')


@id_blueprint.route('/list_of_unconfirmed_persons')
@login_required
def list_of_unconfirmed_persons():
    all_ids = db.session.query(Birth,ID).filter(birthday(Birth.birth_year) >= 18, Birth.has_id == False).all()
    if current_user.username == 'IDAdmin':
        return render_template('list_of_unconfirmed_persons.html', ids=all_ids)
    else:
        flash('Error! Incorrect permissions to access this record.', 'error')
        return render_template('403.html')



@id_blueprint.route('/add_id/<birth_id>', methods=['GET', 'POST'])
@login_required
def add_id(birth_id):
    
    id_number = id_generator()
    new_id = ID(id_number, birth_id)
    db.session.add(new_id)
    birth = Birth.query.get_or_404(birth_id)
    birth.has_id = True;
    db.session.commit()
    if current_user.username == 'IDAdmin':
        flash('New Identification Details, {}, added!'.format(id_number), 'success')
        return redirect(url_for('id.index'))
    else:
        flash_errors(form)
        flash('ERROR! Record was not added.', 'error')
 
    return render_template('add_id.html', form=form)



# @id_blueprint.route('/add_id', methods=['GET', 'POST'])
# @login_required
# def add_id():    
#     form = AddIDForm()
#     if request.method == 'POST':
#         if form.validate_on_submit():
#             filename = images.save(request.files['profile_image'])
#             url = images.url(filename)
#             new_id = ID(form.id_number.data, form.birth_id.data, filename, url)
#             db.session.add(new_id)
#             db.session.commit()
#             flash('New Identification Details, {}, added!'.format(new_id.id_number), 'success')
#             return redirect(url_for('id.list_of_unconfirmed_persons'))
#         else:
#             flash_errors(form)
#             flash('ERROR! Record was not added.', 'error')
 
#     return render_template('add_id.html', form=form)


@id_blueprint.route('/id_detail/<id_card_id>')
def id_details(id_card_id):
    id_with_birth = db.session.query(ID, Birth).join(Birth).filter(ID.id == id_card_id).first()
    if id_with_birth is not None:        
        if current_user.is_authenticated and current_user.username == 'IDAdmin':
            return render_template('id_details.html', id_card=id_with_birth)
        else:
            flash('Error! Incorrect permissions to access this record.', 'error')
    else:
        flash('Error! Record does not exist.', 'error')

project/templates/add_birth.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}
 
<div class="add-birth">
 
<div class="page-header">
 
<h2>Add a New Birth Record</h2>
 
  </div>
 
 
 
<form action="{{ url_for('births.add_birth') }}" method="post">
    {{ form.csrf_token }}
    <dl>
    <div class="form-row">
        <div class="form-group col-md-4">
            {{ render_field(form.child_name, placeholder="Name of Child") }}
        </div>
        <div class="form-group col-md-4">
            {{ render_field(form.father_name, placeholder="Name of Father") }}
        </div>
        <div class="form-group col-md-4">
            {{ render_field(form.mother_name, placeholder="Name of Mother") }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            {{ render_field(form.birth_year, placeholder="Year of Birth") }}
        </div>
        <div class="form-group col-md-4">
            {{ render_field(form.gender, placeholder="Gender") }}
        </div>        
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            {{ render_field(form.birth_county, placeholder="County of Birth") }}
        </div>        
    </div>    
</dl>
    
    <button class="btn btn-sm btn-success" type="submit">Add Birth Record</button>
  </form>
 
</div>
 
 
{% endblock %}

project/templates/add_id.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
 
<div class="add-recipe">
  <div class="page-header">
    <h2>Add Identification Details</h2>
  </div>
  <form action="{{ url_for('id.add_id', birth_id=birth_id) }}" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.id_number, placeholder="Enter ID Number") }}
      {{ render_field(form.birth_id, placeholder="Enter Birth ID") }}
      {{ render_field(form.profile_image) }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Add Details to Profile</button>
  </form>
</div>
 
{% endblock %}

project/templates/admin_view_users.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="admin-view-users">
  <div class="page-header">
    <h2>Administrative Page: List of Users</h2>
  </div>

  <div class="row">
    <table class="table table-striped" id="admin_list_of_users">
      <thead>
        <tr>
          <th>User ID</th>
          <th>Email</th>
          <th>Role</th>
          <th>Registration Date</th>
          <th>Email Confirmed?</th>
          <th>Email Confirmed On</th>
          <th>Last Login</th>
          </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td> {{ user.id }} </td>
            <td> {{ user.email }} </td>
            <td> {{ user.role }} </td>
            <td> {{ user.registered_on }} </td>
            <td> {{ user.email_confirmed }} </td>
            <td> {{ user.email_confirmed_on }}% </td>
            <td> {{ user.last_logged_in }} </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

project/templates/birth_with_ID.html
{% extends "layout.html" %}
{% block content %}
 
<div class="user-profile">
  <div class="page-header">
    <h2>{{ birth.Birth.child_name }}</h2>
  </div>
 
  <div class="row">
    <div class="card panel-primary">
      <div class="card-header">Date of Birth</div>
      <div class="card-body">{{ birth.Birth.birth_date }}</div>
    </div> 
    
 
    <div class="card panel-primary">
      <div class="card-header">County</div>
      <div class="card-body">{{ birth.Birth.birth_county }}</div>
    </div>

    {% if birth.ID.image_url %}
      <img src="{{ birth.Birth.image_url }}" alt="{{ birth.ID.image_filename }}" style="width:600px;height:450px;">
    {% endif %}
 
  </div>
</div>
 
{% endblock %}

project/templates/email_confirmation.html
{# project/templates/email_confirmation.html #}
 
Your account on the Integrated Voting Registration System was successfully created.
Please click the link below to confirm your email address and
activate your account:
  
<a href="{{ confirm_url }}">{{ confirm_url }}</a>
 
--
Questions? Comments? Email mikegachunji@gmail.com.

project/templates/email_password_reset.html
{# project/templates/email_password_reset.html #}
 
You requested that the password for your Integrated Voter Registration System account be reset.
Please click the link below to reset your password:
 
<p>
<a href="{{ password_reset_url }}">{{ password_reset_url }}</a>
</p>
 
<p>
--<br>
Questions? Comments? Email mikegachunji@gmail.com.
</p>

project/templates/id_details.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>{{ id_card.Birth.child_name }}</h2>
  </div>
 
  <div class="row">
    <div class="col-sm-6">
    <div class="card panel-primary">
      <div class="card-header">Identification Number</div>
      <div class="card-body">{{ id_card.ID.id_number }}</div>
    </div>    

    <div class="card panel-primary">
      <div class="card-header">County</div>
      <div class="card-body">{{ id_card.Birth.birth_county }}</div>
    </div>
    

    {% if id_card.ID.image_url %}
      <img src="{{ id_card.ID.image_url }}" alt="{{ id_card.ID.image_filename }}" style="width:600px;height:450px;">
    {% endif %}
 
  </div>
</div>`
 

{% endblock %}

project/templates/ids.html
{% extends "layout.html" %}
{% block content %}

    <div class="page-header">
      <h2>Allocated ID Numbers</h2>
    </div>
    <div class="row">
      <div class="col-md-4">
        <table class="table table-striped" id="owned_stock_table">
          <thead>
      <tr>
        <th>Name</th>
        <th>Identification Number</th>
        <th>Date of Birth</th>
        <th>County</th>             
      </tr>
    </thead>
    <tbody>
      {% for id in ids %}
      <tr>
        <td><a href="{{ url_for('id.id_details', id_card_id=id.ID.id) }}">{{ id.Birth.child_name }}</td>
        <td>{{ id.ID.id_number }}</td>
        <td>{{ id.Birth.birth_year }}</td>
        <td>{{ id.Birth.birth_county }}</td>       
        
      </tr>
      {% endfor %}
    </tbody>
    </table>
   </div>
 </div>

{% endblock %}

project/templates/password_change.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
 
<div class="user-profile">
  <div class="page-header">
    <h2>Password Change</h2>
  </div>
 
  <form action="{{ url_for('users.user_password_change') }}" method="POST">
  {{ form.csrf_token }}
    <dl>
      {{ render_field(form.password, placeholder="Enter New Password") }}
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Update</button>
  </form>
</div>
 
{% endblock %}

project/templates/person_details.html
{% extends "layout.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}

<div class="user-profile">
  <div class="page-header">
    <h2>{{ voters.Birth.child_name }}</h2>
  </div>
 
  <div class="row">
    <div class="col-sm-6">
    <div class="card panel-info">
        <div class="card-header">Account Actions</div>
        <div class="card-body"><a href="{{ url_for('births.mark_as_deceased', birth_id=voters.Birth.id) }}">Mark as Deceased</a></div>               
      </div>
    <div class="card panel-primary">
      <div class="card-header">Identification Number</div>
      <div class="card-body">{{ voters.ID.id_number }}</div>
    </div>
 
    <div class="card panel-primary">
      <div class="card-header">Year of Birth</div>
      <div class="card-body">{{ voters.Birth.birth_year }}</div>
    </div>

    <div class="card panel-primary">
      <div class="card-header">County</div>
      <div class="card-body">{{ voters.Birth.birth_county }}</div>
    </div>    

    {% if voters.ID.image_url %}
      <img src="{{ voters.ID.image_url }}" alt="{{ voters.ID.image_filename }}" style="width:600px;height:450px;">
    {% endif %}
 
  </div>
</div>`
 

{% endblock %}

project/templates/qualified_id_list.html
{% extends "layout.html" %}
{% block content %}

    <div class="page-header">
      <h2>Qualified Persons for ID Card Allocation</h2>
    </div>
    <div class="row">
      <div class="col-md-4">
        <table class="table table-striped" id="owned_stock_table">
          <thead>
      <tr>
        <th>Name</th>
        <th>Date of Birth</th>
        <th>County</th>
        <th>Constituency</th>
        <th>Ward</th>        
      </tr>
    </thead>
    <tbody>
      {% for birth in births %}
      <tr>
        <td><a href="{{ url_for('id.add_id_number', birth_id=birth.id) }}">{{ birth.child_name }}</td>
        <td>{{ birth.birth_date }}</td>
        <td>{{ birth.birth_county }}</td>
        <td>{{ birth.birth_constituency }}</td>
        <td>{{ birth.birth_ward }}</td>
        
      </tr>
      {% endfor %}
    </tbody>
    </table>
   </div>
 </div>

{% endblock %}

project/templates/search_new.html
{% extends "layout.html" %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}
 
<div class="add-recipe">
  <div class="page-header">
    <h2>Search</h2>
  </div>
  <form method=post>
    {{ form.csrf_token }}
    <dl>
      {{ render_field(form.select) }}
      {{ render_field(form.select1) }}
      {{ render_field(form.search) }}      
    </dl>
    <button class="btn btn-sm btn-success" type="submit">Search</button>
  </form>
</div>
 
{% endblock %}

project/templates/unregistered_ids.html
{% extends "layout.html" %}
{% block content %}

    <div class="page-header">
      <h2>Qualified Persons for ID Card Allocation</h2>
    </div>
    <div class="row">
      <div class="col-md-4">
        <table class="table table-striped" id="owned_stock_table">
          <thead>
      <tr>
        <th>Name</th>
        <th>Date of Birth</th>
        <th>County</th>
        <th>Constituency</th>
        <th>Ward</th>        
      </tr>
    </thead>
    <tbody>
      {% for birth in births %}
      <tr>
        <td><a href="{{ url_for('id.add_id_number', birth_id=birth.id) }}">{{ birth.child_name }}</td>
        <td>{{ birth.birth_date }}</td>
        <td>{{ birth.birth_county }}</td>
        <td>{{ birth.birth_constituency }}</td>
        <td>{{ birth.birth_ward }}</td>
        
      </tr>
      {% endfor %}
    </tbody>
    </table>
   </div>
 </div>

{% endblock %}